apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: example-pipeline-template
  title: Create Pipeline
  description: Create a new Pipeline with example documentation
  tags:
    - pipeline
spec:
  owner: group:github
  type: system

  parameters:
    - title: About
      required:
        - name
        - description
        - owner
      properties:
        name:
          title: Name
          type: string
          description: The unique name of this pipeline
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Description of this pipeline
        owner:
          title: Owner
          type: string
          description: Owner of this pipeline
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              - kind: Group

  steps:
    - id: fetch
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
          - .github/workflows/*
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          project_slug: ONS-Innovation/${{ parameters.name }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        repoUrl: github.com?owner=ONS-Innovation&repo=${{ parameters.name }}
        description: ${{ parameters.description }}
        repoVisibility: public
        defaultBranch: main
        protectEnforceAdmins: false
        access: ${{ user.entity.metadata.annotations['github.com/user-login'] }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
